### ISSUE TITLE
Managem spec 2048

### ISSUE THREAD

**Issue by tom0815** [gemforce-team/gemforce#2]
Hi,
here is the link to the zipped table:
https://drive.google.com/file/d/0Bw0t6AblrnpqS0RZVEtieFhQVWc/view?usp=sharing

Greetings from Dresden,
Tom

**Comment by 12345ieee** [comment]
Thank you.
You gained a mention on [gemforce-tables](https://github.com/gemforce-team/gemforce-tables)'s README (I realize it's a poor compensation for all the CPU cycles used, but it's everything I can do).
If you prefer being listed with a different (user)name let me know.

Bye from Italy.
Andrea
