### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by SarahKirksey** [gemforce-team/gemforce#9]
I seem to recall reading somewhere along my recent trekking that I can help out the Gemforce project/team if I have spare processing power that I'm willing to provide. (I've tried to find the exact spot I read that, but I can't seem to find it.) I've also read that if I want to help out, I should create a new issue here, so that's what I'm doing.

I've got a fairly beefy computer and I'd like to help out; I assume the idea is that you've got some supergemming calculations that you'd want me to perform, which I'd be more than happy to do.

I also have a decent amount of programming experience, as well as some experience with C++, but I can't guarantee that I'll have the time/energy/focus to make any real contributions... and I'd be largely useless for quite a while unless someone helped orient me in the code, since I only have a rough grasp of how the project is set up.

**Comment by 12345ieee** [comment]
Oh, man, now it's a bit late :smile: .

GC2 needed more computational power for spec recipes, because they scale horribly and I couldn't go over 2k, but for GCFW, only combines are needed, and by this point my laptop has basically done all the ones that are feasible with current algorithms.

I do have some things I'd like, even if I do feel a little bad making you waste electricity on it, like crit 256k -> 512k and bleed 2M -> 4M.

The way the programs are made, they'll pull 100% of one core (a real 100% IPC throughput) and a few gigs of RAM.
Finishing one of the 2 tasks outlined here will take several CPU days.

If after this you are still interested, write here what architecture and OS are you on, and I'll give you all the material.

**Comment by 12345ieee** [comment]
Btw, I assumed you played GCFW, but if you play GC2, I have other stuff, like kill specs.

**Comment by SarahKirksey** [comment]
I haven't gotten FW yet, no. That said, I'm happy to help out with whatever is lacking.

As for OS, I've got Windows 10 Home.
For architecture, I'm not sure what the exact information you're looking for would be. My CPU is an [Intel Xeon X5472](https://ark.intel.com/content/www/us/en/ark/products/34447/intel-xeon-processor-x5472-12m-cache-3-00-ghz-1600-mhz-fsb.html), and I have 12 gigs of RAM in total. (It used to be 16, but one of the sticks went bad. I removed the pair and haven't bothered figuring out which one is the bad one.) With everything I'm _currently_ doing on my computer, I'm generally around 35% CPU usage and 70% memory usage. If worse comes to worst, I can probably close a couple of things for a few days. :)

**Comment by 12345ieee** [comment]
Man, that's serious power.
I need a couple of days to plan so I don't make you waste electricity, then I'll send you a windows exe.

Any preference? There's been some recent theoretical developments on leech recipes and I'd like to extend them, good for both GC2 and GCFW.

Can you also find where I ask for computational help? I'd like to edit it.

**Comment by SarahKirksey** [comment]
As I said before, I tried to figure out where I got the idea that I could volunteer CPU time, and I couldn't. Maybe I misread or misunderstood something, or maybe it was on some weird esoteric branch of my data crawl that I just haven't thought to look there. I will continue to keep an eye out, but I doubt I'll ever run into it.

As for preferences on what to work on, I'd love to help you explore those theoretical developments on leech recipes.

**Comment by SarahKirksey** [comment]
I _may_ have gotten the idea from reading the README.md on [Gemforce Tables](https://github.com/gemforce-team/gemforce-tables), which mentioned "People who contributed with some computational power", combined with the oft-repeated note
> If this project helped you and you wish to help by contributing, please contact us, leaving a new issue or opening a new pull request. You can also help by donating some money for our time:

It's a stretch, but that's what happens when you're in that mindset where you hear what you want to hear instead of what was said. =)

**Comment by 12345ieee** [comment]
Oh man, I have to delete that!
Thank you.

**Comment by 12345ieee** [comment]
So, theoretical developments are impressive enough that I have to rewrite everything, and significant  computational power may not even be needed anymore.

I'll keep you updated.

**Comment by 12345ieee** [comment]
I have to close this, I thank you for the offer, but there is really nothing to compute now, it'll take weeks or months to analyze the new advances and get at the point I have enough stuff to explore that I want to borrow CPU time.

Thank you for your offer.
